server:
  # 服务器的HTTP端口，默认为80
  port: 2222
  servlet:
    # 应用的访问路径
    context-path: /
    tomcat:
      # tomcat的URI编码
      uri-encoding: UTF-8
      # tomcat最大线程数，默认为200
      max-threads: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare-threads: 30

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/poplar
        username: root
        password:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
# Spring配置
#spring:
#  profiles:
#    active: dev

#    # 禁用缓存
#    cache: false

# MyBatis
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.phoenix..dao.entity
  #  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations:  classpath:mapper/*Mapper.xml